- name: Pull Nexus Docker image
  docker_image:
    name: "{{ nexus_image }}"
    source: pull

- name: Run Nexus container
  docker_container:
    name: "{{ nexus_container_name }}"
    image: "{{ nexus_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ nexus_port }}:8081"
      - "8082:8082"

- name: Wait for Nexus to start
  wait_for:
    port: "{{ nexus_port }}"
    delay: 10
    timeout: 300

- name: Get admin password
  command: docker exec {{ nexus_container_name }} cat /nexus-data/admin.password
  register: admin_password
  changed_when: false

- name: Display admin password
  debug:
    var: admin_password.stdout

- name: Print Nexus URL
  ansible.builtin.debug:
    msg: "Nexus is available at http://{{ ansible_host }}:8081"
    verbosity: 0

# - name: Reset admin password
#   uri:
#     url: "http://localhost:{{ nexus_port }}/service/rest/v1/security/users/admin/change-password"
#     method: PUT
#     body_format: json
#     body: '{"password": "your_new_password_here"}'
#     headers:
#       Content-Type: "application/json"
#     user: admin
#     password: "{{ admin_password.stdout }}"
#     force_basic_auth: yes
#     status_code: 204
#   register: password_reset
#   until: password_reset.status == 204
#   retries: 5
#   delay: 10

# - name: Inform about password reset
#   debug:
#     msg: "Admin password has been reset. Please use the new password for future logins."