- name: Create Prometheus system group
  group:
    name: prometheus
    system: yes
    state: present

- name: Create Prometheus system user
  user:
    name: prometheus
    system: yes
    group: prometheus
    create_home: no
    shell: /usr/sbin/nologin

- name: Create Prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - "{{ prometheus_install_dir }}"
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"

- name: Download and extract Prometheus
  unarchive:
    src: "{{ prometheus_url }}"
    dest: "{{ prometheus_install_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: "{{ prometheus_install_dir }}/prometheus"
    owner: prometheus
    group: prometheus

- name: Create Prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: prometheus
    group: prometheus
    mode: '0644'

- name: Create Prometheus systemd service file
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'

- name: Ensure Prometheus service is started and enabled
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes

- name: Print Prometheus URL
  ansible.builtin.debug:
    msg: "Prometheus is available at http://{{ ansible_host }}:3000"
    verbosity: 0